*&---------------------------------------------------------------------*
*&  Include           ZOR_RT_CASH_TRANSFER_TOP
*&---------------------------------------------------------------------*
TYPES: BEGIN OF gsty_export_log,
         id                         TYPE string,
         fk_export_table_definition TYPE string,
         description                TYPE string,
         record_id                  TYPE string,
       END OF gsty_export_log,

       BEGIN OF gsty_header,
         id                   TYPE string,
         fk_store             TYPE string,
         fk_pos               TYPE string,
         trans_date           TYPE string,
         fk_user              TYPE string,
         receipt_barcode      TYPE string,
         ptype                TYPE string,
         status               TYPE string,
         document_no          TYPE string,
         customer_code        TYPE string,
         address_on_doc       TYPE string,
         name_on_doc          TYPE string,
         num                  TYPE string,
         gross_total          TYPE string, "ex
         gross_vat_total      TYPE string,
         discount_on_total    TYPE string,
         discount_on_lines    TYPE string,
         rounding_total       TYPE string,
         taxfree_refund_total TYPE string,
         custom_text          TYPE string,
         void_description     TYPE string,
         option_bitflag       TYPE string,
         fk_customer          TYPE string,
       END OF gsty_header,


       BEGIN OF gsty_sale,
         id               TYPE string,
         line_no          TYPE string,
         status           TYPE string,
         vat_percent      TYPE string,
         amount           TYPE string,
         fk_unit          TYPE string,
         total_price      TYPE string,
         vat_total        TYPE string,
         barcode          TYPE string,
         code             TYPE string,
         sale_type        TYPE string,
         fk_seller        TYPE string,
         fk_return_reason TYPE string,
       END OF gsty_sale,

       BEGIN OF gsty_payment,
         id                  TYPE string,
         status              TYPE string,
         fk_payment_type     TYPE string,
         payment_type        TYPE string,
         payment_type_detail TYPE string,
         payment_total       TYPE string,
         currency_total      TYPE string,
         custom_text         TYPE string,
         serial_no           TYPE string,
       END OF gsty_payment,

       BEGIN OF gsty_discount,
         id                 TYPE string,
         line_no            TYPE string,
         parent_line        TYPE string,
         discount_type      TYPE string,
         discount_code      TYPE string,
         amount             TYPE string,
         parameter_2        TYPE string,
         fk_campaign        TYPE string,
         fk_discount_reason TYPE string,
       END OF gsty_discount,

       BEGIN OF gsty_discount_detail,
         id                      TYPE string,
         fk_transaction_header   TYPE string,
         fk_transaction_sale     TYPE string,
         fk_transaction_discount TYPE string,
         amount                  TYPE string,
       END OF gsty_discount_detail,

       BEGIN OF gsty_result,
         id                    TYPE string,
         fk_transaction_header TYPE string,
         parameter_1           TYPE string,
         parameter_2           TYPE string,
         parameter_3           TYPE string,
         code                  TYPE string,
         type                  TYPE string,
       END OF gsty_result,

       BEGIN OF gsty_customer,
         id             TYPE string,
         code           TYPE string,
         name           TYPE string,
         tc_identity_no TYPE string,
       END OF gsty_customer,

       BEGIN OF gsty_customer_extension,
         id             TYPE string,
         fk_customer    TYPE string,
         tax_office     TYPE string,
         tax_number     TYPE string,
         address_letter TYPE string,
         cell_phone     TYPE string,
       END OF gsty_customer_extension,

       BEGIN OF gsty_description,
         id          TYPE string,
         description TYPE string,
       END OF gsty_description,

       BEGIN OF gsty_user,
         id   TYPE string,
         code TYPE string,
         name TYPE string,
       END OF gsty_user,

       BEGIN OF gsty_seller,
         id   TYPE string,
         name TYPE string,
       END OF gsty_seller,

       BEGIN OF gsty_temp,
         id                    TYPE string,
         fk_store              TYPE string,
         fk_pos                TYPE string,
         num                   TYPE string,
         trans_date            TYPE string,
         fk_user               TYPE string,
         receipt_barcode       TYPE string,
         ptype                 TYPE string,
         status                TYPE string,
         document_no           TYPE string,
         trans_end_date        TYPE string,
         fk_customer           TYPE string,
         customer_code         TYPE string,
         gross_total           TYPE string,
         gross_vat_total       TYPE string,
         discount_on_total     TYPE string,
         discount_on_lines     TYPE string,
         rounding_total        TYPE string,
         taxfree_refund_total  TYPE string,
         custom_text           TYPE string,
         void_description      TYPE string,
         fk_closure            TYPE string,
         fk_transaction_header TYPE string,
         fk_user_sign          TYPE string,
         name_on_doc           TYPE string,
         address_on_doc        TYPE string,
         option_bitflag        TYPE string,
         create_date           TYPE string,
         fk_user_create        TYPE string,
         modify_date           TYPE string,
         fk_user_modify        TYPE string,
         fk_store_lu           TYPE string,
         fk_store_ls           TYPE string,
         updateseq             TYPE string,
       END OF  gsty_temp,

       BEGIN OF gsty_payment_type,
         id  TYPE c LENGTH 19,
         num TYPE c LENGTH 19,
       END OF gsty_payment_type,

       BEGIN OF gsty_output_line ,
         line(256) TYPE c,
       END OF gsty_output_line,

       BEGIN OF gsty_zreport ,
         tarih                TYPE string,
         sube                 TYPE string,
         kasa_adi             TYPE string,
         kasa_no              TYPE string,
         sicil_no             TYPE string,
         z_numarasi           TYPE string,
         toplam_hasilat       TYPE string,
         toplam_indirim       TYPE string,
         fisli_gunluk_hasilat TYPE string,
         gunluk_kdv_toplami   TYPE string,
         gecerli_fis_sayisi   TYPE string,
         urun_ind_toplami     TYPE string,
         toplam_indirimi      TYPE string,
         nakit                TYPE string,
         diger                TYPE string,
         kredi_karti          TYPE string,
         fatura_sayisi        TYPE string,
         fatura_gn_hasilat    TYPE string,
         fatura_gn_kdv        TYPE string,
       END OF gsty_zreport ,


       BEGIN OF gsty_reason,
         id          TYPE string,
         description TYPE string,
         parent_line TYPE string,
       END OF gsty_reason,
       tt_reason TYPE STANDARD TABLE OF gsty_reason,

       BEGIN OF gsty_camp,
         id          TYPE string,
         description TYPE string,
         parent_line TYPE string,
       END OF gsty_camp,
       tt_camp TYPE STANDARD TABLE OF gsty_camp,

       BEGIN OF gsty_eft_pos,
         authorization_num       TYPE string,
         amount                  TYPE string,
         bonus                   TYPE string,
         installment_count       TYPE string,
         card_num                TYPE string,
         terminal_id             TYPE string,
         batch_num               TYPE string,
         trace_num               TYPE string,
         card_type               TYPE string,
         trans_type              TYPE string,
         fk_payment_type_eft_pos TYPE string,
       END OF gsty_eft_pos,

       BEGIN OF gsty_receipt,
         header          TYPE                   gsty_header,
         temp            TYPE                   gsty_header,
         sale            TYPE STANDARD TABLE OF gsty_sale               WITH NON-UNIQUE KEY table_line,
         sale_cancel     TYPE STANDARD TABLE OF gsty_sale               WITH NON-UNIQUE KEY table_line,
         payment         TYPE STANDARD TABLE OF gsty_payment            WITH NON-UNIQUE KEY table_line,
         discount        TYPE STANDARD TABLE OF gsty_discount           WITH NON-UNIQUE KEY table_line,
         discount_detail TYPE STANDARD TABLE OF gsty_discount_detail    WITH NON-UNIQUE KEY table_line,
         result          TYPE STANDARD TABLE OF gsty_result             WITH NON-UNIQUE KEY table_line,
         customer        TYPE STANDARD TABLE OF gsty_customer           WITH NON-UNIQUE KEY table_line,
         customer_ex     TYPE STANDARD TABLE OF gsty_customer_extension WITH NON-UNIQUE KEY table_line,
         store           TYPE STANDARD TABLE OF gsty_description        WITH NON-UNIQUE KEY table_line,
         pos             TYPE STANDARD TABLE OF gsty_description        WITH NON-UNIQUE KEY table_line,
         user            TYPE STANDARD TABLE OF gsty_user               WITH NON-UNIQUE KEY table_line,
         seller          TYPE STANDARD TABLE OF gsty_seller             WITH NON-UNIQUE KEY table_line,
         reason          TYPE STANDARD TABLE OF gsty_description        WITH NON-UNIQUE KEY table_line,
         campaign        TYPE STANDARD TABLE OF gsty_camp               WITH NON-UNIQUE KEY table_line,
         discount_reas   TYPE STANDARD TABLE OF gsty_reason             WITH NON-UNIQUE KEY table_line,
         eft             TYPE STANDARD TABLE OF gsty_eft_pos            WITH NON-UNIQUE KEY table_line,
       END OF gsty_receipt,

       out_line         TYPE STANDARD TABLE OF gsty_output_line WITH NON-UNIQUE KEY table_line,
       tt_export_log    TYPE TABLE OF gsty_export_log,
       tt_header        TYPE TABLE OF gsty_header,
       tt_receipts      TYPE TABLE OF gsty_receipt,
       tt_zreport       TYPE TABLE OF gsty_zreport,
       tt_payment_types TYPE TABLE OF gsty_payment_type,

       BEGIN OF gsty_trns,
         id              TYPE string,
         retailstoreid   TYPE /posdw/tibq-retailstoreid,
         businessdaydate TYPE /posdw/tibq-businessdaydate,
         operationtype   TYPE c LENGTH 1,
       END OF gsty_trns.
DATA: gv_done            TYPE xfeld.

DATA : gt_log TYPE TABLE OF zor_cash_id,
       gs_log LIKE LINE OF gt_log.

DATA: gr_root  TYPE REF TO cx_root,
      gr_root2 TYPE REF TO cx_root,
      gv_text  TYPE char200.
TABLES : zor_cash_id.
DATA: id TYPE string.
DATA: gv_er TYPE string.

SELECTION-SCREEN BEGIN OF BLOCK b01 WITH FRAME TITLE text-001.
*PARAMETERS : p_id LIKE zor_cash_id-id.
PARAMETERS : p_satis RADIOBUTTON GROUP gr1 DEFAULT 'X',
             p_aski  RADIOBUTTON GROUP gr1.
*             p_z     RADIOBUTTON GROUP gr1.
PARAMETERS: p_limit TYPE i DEFAULT '1000'.
*PARAMETERS: p_budat TYPE sy-datum DEFAULT sy-datum.
SELECTION-SCREEN END OF BLOCK b01.
